# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
jQuery ->
  drawChart = ->
    counter_id = $('#counter_id').val()
    range_type = $('#range_type').val()
    jsonData = $.ajax(
      url: '/entries/get_reports?counter_id=' + counter_id + '&range_type=' + range_type
      dataType: 'json'
      async: false).responseText
    obj = JSON.parse(jsonData)
    cols = obj.cols
    rows = obj.rows
    subtitle = obj.subtitle
    dataTable = []
    dataTable.push cols
    for a of rows
      `a = a`
      dataTable.push rows[a]
    data = google.visualization.arrayToDataTable(dataTable)
    options =
      chart:
        title: 'Feedback Reports'
        subtitle: subtitle
      colors: ['#4285f4', '#0f9d58', '#f4b400', '#db4437']
    chart = new (google.charts.Bar)(document.getElementById('columnchart_material'))
    chart.draw data, google.charts.Bar.convertOptions(options)
    return

  $('#counter_id, #range_type').select2 theme: 'bootstrap'
  google.charts.load 'current', 'packages': [ 'bar' ]
  google.charts.setOnLoadCallback drawChart
  $('#counter_id, #range_type').on 'change', ->
    drawChart()
    return

# ---
# generated by js2coffee 2.2.0
